---
es_cluster_name: "elk-cluster"
es_version: "8.x"         # 仅作标记；repo 将安装最新可用
es_heap_size: "2g"        # 根据内存调整
es_network_host: "0.0.0.0"

# 集群发现与 master 节点名单（使用 inventory hostnames 或 IP）
es_seed_hosts:
  - "172.20.10.3"
  - "172.20.10.5"
  - "172.20.10.6"

es_initial_master_nodes:
  - "host1"
  - "host2"
  - "host3"
